<h3 class="sectiontitle"><div class="helplink"><a href="${location}guide#toolbox"><img alt="?" src="${location}help_button2.gif" class="helpicon" title="What are these ?" /></a></div><span style="line-height:26px;">Toolbox</span></h3>
  <ul class="toolbox">
   <li><a href="${location}add">Add a bookmark</a></li>
   <li><a href="${location}addgroup">Create a new group</a></li>
   <li><a href="${location}addtagnote">Create a tag note</a></li>
   <li><a href="${location}retag">Rename a tag</a></li>
   <li><a href="${location}bookmarklets">Bookmarklets</a></li>
   <li><a href="${location}upload">Import from local file</a></li>
   <li><a href="${location}library/export">Export my library</a></li>
  </ul>
