<h2>Wiki Edit Help</h2>
<p>
How to create headings:

<pre class="wikiedithelppre">
= Page Title =

== Section Heading ==

=== Sub-heading ===
</pre>
</p>
<p>
Formatting text:

<pre class="wikiedithelppre">
''italic text''

*bold text*

**highlighted text**
</pre>
</p>
<p>
Lists:

<pre class="wikiedithelppre">
Leave four spaces before
the asterix:

     * Bullet item one
     * Bullet item two
     * ...

or the number:

     1. Number one
     2. Number two
     3. ...
</pre>
</p>
<p>
How to link to other Community Pages:

<pre class="wikiedithelppre">
MultiWordPageName

or

wikilink=Singlewordname=
</pre>
</p>
<p>
How to link to general web pages:

<pre class="wikiedithelppre">
[URL|text]

e.g.

[http://nature.com/|click]
</pre>
</p>
<p>
How to link to Profile Pages:

<pre class="wikiedithelppre">
User:username
</pre>
</p>
<p>
How to link to a user's library:

<pre class="wikiedithelppre">
@>User(username)
</pre>
</p>
<p>
Horizontal rule:
<pre class="wikiedithelppre">
----
</pre>
</p>
<p>
Table:
<pre class="wikiedithelppre">
| *head 1* | *head 2* |
|       A  | item     |
|       B  | item     |
</pre>
</p>
<p>
Blockquotes:
<pre class="wikiedithelppre">
Leave four space before
the text:

    I think therefore...

</pre>
</p>
<br />
<p align="center"><a href="${location}wiki/">Community Pages Home</a></p>
