<h2>Community Profile</h2>

<p>This is a $sitename Community Profile.  Every Connotea user can freely 
create their own profile page.  Unlike the other <a href="/wiki/User:">Community 
Pages</a>, only the owner of this page can edit it.
</p>
<p>
To create your own profile page, follow the link from your <a href="${location}library">library</a>.
</p>
<p>
You don't need any special technical knowledge to edit your page.
</p>

