#!/usr/bin/perl
#
# Copyright 2005 Nature Publishing Group
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# The 'add' script is a test script that adds bookmarks.

use strict;
use Bibliotech;

my $bibliotech = new Bibliotech;

if (@ARGV) {
  add(@ARGV);
}
else {
  while(<>) {
    chomp;
    next if m|^\#|;
    add(split /\t/);
  }
}

sub add {
  my ($username, $uri, $description, @tags) = @_;
  my ($user) = Bibliotech::User->search(username => $username);
  my $user_bookmark = $bibliotech->add(user_id => $user, uri => $uri, description => $description, tags => \@tags);
  print $user_bookmark->bookmark->url, " added.\n";
}
