#!/usr/bin/perl
use strict;
use warnings;
use lib '..';
use Bibliotech::Fake;
use Bibliotech::Component::Wiki;

my $bibliotech = Bibliotech::Fake->new;
my $wiki_comp = Bibliotech::Component::Wiki->new({bibliotech => $bibliotech});
my $wiki = $wiki_comp->wiki_obj;
print map { s/([^\n])\z/$1\n/; $_ } map { warn "$_\n"; scalar($wiki->retrieve_node($_)) } @ARGV;
