#!/bin/bash
# correct permissions etc post-checkout
. /root/bin/connotea_vars
[ "$1" == "-d" ] || cd $BASE/bibliotech
chmod a+x memcached_wrapper
chown apache html/antispam_captcha.csv 
chown apache html/antispam_score.csv
chown apache html/captcha
chmod a+x bibutils/bib2xml
chmod a+x bibutils/copac2xml
chmod a+x bibutils/end2xml
chmod a+x bibutils/isi2xml
chmod a+x bibutils/med2xml
chmod a+x bibutils/modsclean
chmod a+x bibutils/ris2xml
chmod a+x bibutils/xml2bib
chmod a+x bibutils/xml2end
chmod a+x bibutils/xml2ris
echo "Make-Executable completed OK."
