#!/bin/bash
# correct permissions etc post-checkout
. /root/bin/connotea_vars
[ "$1" == "-d" ] || cd $BASE/bibliotech
chmod a+x admin_util/memcached_wrapper
if [ -e bibutils -a -e bibutils/xml2ris ]; then
  cd bibutils
  chmod a+x bib2xml
  chmod a+x copac2xml
  chmod a+x end2xml
  chmod a+x endx2xml
  chmod a+x isi2xml
  chmod a+x med2xml
  chmod a+x modsclean
  chmod a+x ris2xml
  chmod a+x xml2bib
  chmod a+x xml2end
  chmod a+x xml2isi
  chmod a+x xml2ris
  chmod a+x xml2word
  cd ..
fi
[ "$1" != "-d" ] && cd $HTML
[ "$1" == "-d" ] && cd $SITE
chown apache antispam_captcha.csv
chown apache antispam_score.csv
chown apache captcha
echo "Make-Executable completed OK."
