#!/bin/bash

. /root/bin/connotea_vars
bconfig=$CONF
hconfig=$APCONF
phtml=$HTML/paused.html
htmltime='4 hours ago'
tmpfile=/tmp/pause_connotea_temp
viewer='/usr/bin/links -dump'

# if the html file is older than two hours, warn user that it should be updated
touch -d "$htmltime" $tmpfile
if [ "$phtml" -ot "$tmpfile" ]; then
  echo
  echo [This is the current paused message in $phtml:]
  echo
  $viewer $phtml
  echo
  echo [Please update. If this message is ok, please touch the file timestamp and rerun pause_connotea.]
  echo
  rm -f $tmpfile
  exit 1
else
  rm -f $tmpfile
fi

rm -f $bconfig.bak
perl -i.bak -pe 's/(SERVICE_PAUSED\s*=\s*)false/${1}true/' $bconfig

rm -f $hconfig.bak
perl -i.bak -pe 's/#+(ErrorDocument 503 \/paused.html)/$1/; s/(ErrorDocument 503 \/unavailable.html)/#$1/' $hconfig

echo "Reconfiguration for pause completed OK."
exec /root/bin/restart_connotea
