#!/bin/bash
. /root/bin/connotea_vars
if perl -e "exit('$PWD' =~ m|^$BASE.+| ? 0 : 1)"; then
  echo "You are within the base directory structure which is altered by this script."
  echo "Change directory back to at least $BASE and rerun."
  exit 1
fi
cd $BASE
echo Working...
if [ "$1" == "+c" ]; then
  # fresh checkout
  shift 1
  fresh=1
  [ -e bibliotech_new ] && rm -rf bibliotech_new
  [ -e bibliotech_co ] && rm -rf bibliotech_co
  mkdir bibliotech_co
  cd bibliotech_co
  darcs get $* $REPO || exit 2
  mv $RDIR ../bibliotech_new
  # REPO2 allows files in a separate repo to be overlaid
  # (currently used for large movie files which are awkward in darcs)
  if [ -n "$REPO2" -a -n "$RDIR2" ]; then
    # darcs is just used as a convenient delivery mechanism here
    darcs get $* $REPO2 || exit 2
    cd $RDIR2
    rm -rf _darcs
    cp -ar * ../../bibliotech_new/
    # bibliotech_new now has some "whatsnew" changes but that's ok
    # as long as future pull's from $REPO don't conflict with $REPO2
    cd ..
    rmdir $RDIR2
  fi
  cd ..
  rmdir bibliotech_co
  cd bibliotech_new
else
  # update, preserving local changes
  fresh=0
  [ -e bibliotech_new ] && rm -rf bibliotech_new
  cp -a bibliotech bibliotech_new
  cd bibliotech_new
  darcs pull -a $* || exit 2
fi
perl t/00*.t || exit 3
if [ -d deploy ]; then
  cp -f deploy/* /root/bin/
  for file in /root/bin/*; do head -n1 $file | grep -q '^#!' && chmod a+x $file; done
fi
[ "$fresh" == "1" ] && /root/bin/mkexec_connotea -d
cd ..
[ -e bibliotech_old ] && rm -rf bibliotech_old
mv -f bibliotech bibliotech_old
mv -f bibliotech_new bibliotech
echo "Update completed OK."
exec /root/bin/restart_connotea
